language: python
dist: xenial
  
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

matrix:
  include:
    - python: 3.4
      dist: trusty
    - env:
        - HOUSEKEEPING=1
      install: skip
      before_script: ./bin/fetch-configlet
      script:
        - ./bin/configlet lint .
        - ./bin/check-readmes.sh
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements-travis.txt

before_script:
  - flake8
  
script: 
  - ./test/check-exercises.py
