sudo: false

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements-travis.txt

before_script:
  - flake8
  - ./bin/fetch-configlet
  - ./bin/fetch-topics
  - python -m pytest bin/config_helper.py
  - ./bin/config_helper.py lint

script:
  - ./bin/configlet lint .
  - ./test/check-exercises.py
