language: python
dist: xenial
  
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

matrix:
  include:
    # Python 3.4 not supported in xenial
    - python: 3.4
      dist: trusty
    - env: JOB=HOUSEKEEPING
      install: ./bin/fetch-configlet
      before_script: ./bin/check-readmes.sh
      script: ./bin/configlet lint .
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements-travis.txt

before_script:
  - flake8
  
script: 
  - ./test/check-exercises.py
